services:
  api:
    container_name: api
    image: node:22.14.0-alpine3.20
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    command: /bin/sh -c "npm run build && npm run start"

  postgres:
    container_name: postgres
    image: postgres:17.3
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql

volumes:
  postgres-data:
    driver: local
